### ISSUE TITLE
No Items/Backgrounds

### ISSUE THREAD

**Issue by Ampelo** [ZoltanTheDM/XML-foundry-import#4]
Hi Zoltan, 

I am enjoying the importer however the issue arrive that your list is not showing import items/backgrounds, I hope one day that be optional for us to use when importing a URL.

Thanks for your hard work and keep it going. 

Edit: Just to simplify the list of Add Feats, Add class Features, and so forth does not list Items or Backgrounds, it is a great help if this could be added. 

Dino Heart.

**Comment by ZoltanTheDM** [comment]
I agree this needs to be done and shoudn't be difficult. I have just been busy and distracted from working on this

**Comment by ZoltanTheDM** [comment]
Done in version 0.9.0
