### ISSUE TITLE
Doesnt seem to work on 10+ version of Foundry

### ISSUE THREAD

**Issue by setite80** [ZoltanTheDM/XML-foundry-import#5]
Nothing happens when i want to import

**Comment by ZoltanTheDM** [comment]
I have tested it pretty extensively on foundry 10. I would recommend looking at the console (usually F12) to see if there are any errors when trying to import

**Comment by setite80** [comment]
i think the format of XML im trying to import is not in a way foundry understands

**Comment by setite80** [comment]
commons.js:1703 Error: You are accessing the Item5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly. 

this is the last error i got. imports everything but doesnt show up

**Comment by ZoltanTheDM** [comment]
I haven't been able to reproduce this issue
