### ISSUE TITLE
Can't seem to import background items

### ISSUE THREAD

**Issue by Jamster-XD** [ZoltanTheDM/XML-foundry-import#6]
Hello, I've been looking at this for some time now and can't seem to figure out background item imports.

The features and roll tables are all importing fine, but I can't seem to get the background items themselves working. I can't work out if I'm missing input or if something isn't translating correctly. The console says Completed Import, but when trying to open the item from the compendium it gives an error and doesn't open:

TypeError: An error occurred while rendering ItemSheet5e 130. Cannot read properties of undefined (reading 'added')
    at ItemGrantAdvancement.summaryForLevel (item-grant.mjs:54)
    at item-sheet.mjs:165
    at Array.map (<anonymous>)
    at ItemSheet5e._getItemAdvancement (item-sheet.mjs:159)
    at ItemSheet5e.getData (item-sheet.mjs:101)
    at async ItemSheet5e._render (foundry.js:5108)
    at async ItemSheet5e._render (foundry.js:5822)

```
<background>
<name>Acolyte</name>
<trait>
<name>Description</name>
<text>
You have spent your life in the service of a temple to a specific god or pantheon of gods...
</text>
</trait>
<trait>
<name>Feature: Shelter of the Faithful</name>
<text>
As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity...
</text>
</trait>
<trait>
<name>Suggested Characteristics</name>
<text>
Acolytes are shaped by their experience in temples or other religious communities...
</text>
</trait>
</background>
```

**Comment by ZoltanTheDM** [comment]
I am not able to reproduce the issue. Could you share a the xml section? As well as which version of Foundry and dnd5e system?

XML example:
```xml
<background>
      <name>Acolyte</name>
    [...]
</background>
```

**Comment by Jamster-XD** [comment]
Hello, forgot to comment my xml earlier.

XML version is 0.9.0
Not sure what version 5E was as I just updated it, but it was the most recent release before 2.1.5

**Comment by ZoltanTheDM** [comment]
So I did some testing and I was able to reproduce your error when I downgraded my DnD5e to below 2.1.0.

It seems it is required to run it at at a later version. I will try to add that to the compatibility requirements to `module.json`. But I don't feel terribly motivated to make sure it is backwards compatible

**Comment by Jamster-XD** [comment]
Not to worry, I'll use the new 5E anyway!
Thanks for your help :)
